using System.Collections.ObjectModel;
using System.IO;
using Avalonia.Platform.Storage;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SevenZipExt.Models;
using SevenZipExt.Services;

namespace SevenZipExt.ViewModels;

public partial class CompressWindowViewModel : ViewModelBase
{
    private readonly SevenZipService _sevenZip;
    private readonly SettingsService _settings;
    private bool _updating;
    private bool _isUpdatingArchivePath;
    private bool _archivePathAutoGenerated = true;

    // --- Observable properties ---
    [ObservableProperty] private string _archivePath = "";
    [ObservableProperty] private string _selectedFormat = "7z";
    [ObservableProperty] private string _selectedLevel = "5 - 普通";
    [ObservableProperty] private string _selectedMethod = "";
    [ObservableProperty] private string _selectedDictionarySize = "";
    [ObservableProperty] private string _selectedWordSize = "";
    [ObservableProperty] private string _selectedSolidBlockSize = "";
    [ObservableProperty] private string _selectedThreads = "自动";
    [ObservableProperty] private string _memoryCompress = "";
    [ObservableProperty] private string _memoryDecompress = "";
    [ObservableProperty] private bool _isMethodEnabled = true;
    [ObservableProperty] private bool _isSolidEnabled;
    [ObservableProperty] private bool _isDictionaryEnabled;
    [ObservableProperty] private bool _isWordSizeEnabled;
    [ObservableProperty] private bool _isThreadCountEnabled = true;
    [ObservableProperty] private bool _isEncryptionEnabled;
    [ObservableProperty] private bool _isEncryptFileNamesEnabled;
    [ObservableProperty] private bool _isSfxEnabled = true;
    [ObservableProperty] private bool _isVolumeEnabled = true;
    [ObservableProperty] private bool _isVolumeSplitEnabled;
    [ObservableProperty] private string _volumeSize = "";
    [ObservableProperty] private string _selectedVolumeMode = "";
    [ObservableProperty] private string _selectedVolumePreset = "";
    [ObservableProperty] private string _volumeCustomSize = "";
    [ObservableProperty] private string _selectedVolumeUnit = "MB";
    [ObservableProperty] private string _additionalParams = "";
    [ObservableProperty] private string _updateMethod = "添加并替换文件";
    [ObservableProperty] private string _pathMode = "相对路径";
    [ObservableProperty] private bool _createSfx;
    [ObservableProperty] private bool _compressSharedFiles;
    [ObservableProperty] private bool _deleteAfterCompress;
    [ObservableProperty] private string _password = "";
    [ObservableProperty] private string _passwordConfirm = "";
    [ObservableProperty] private bool _showPassword;
    [ObservableProperty] private string _selectedEncryption = "AES-256";
    [ObservableProperty] private bool _encryptFileNames;
    [ObservableProperty] private bool _isRunning;
    [ObservableProperty] private string _progressText = "";
    [ObservableProperty] private string _patternInput = "";
    [ObservableProperty] private ObservableCollection<string> _selectedSources = new();
    [ObservableProperty] private ObservableCollection<ExclusionItem> _selectedExclusions = new();

    // Password mask character for binding
    public char PasswordMaskChar => ShowPassword ? '\0' : '•';
    partial void OnShowPasswordChanged(bool value) => OnPropertyChanged(nameof(PasswordMaskChar));

    // --- Dynamic option lists (change based on format/method/level) ---
    public ObservableCollection<string> Methods { get; } = new();
    public ObservableCollection<string> DictionarySizes { get; } = new();
    public ObservableCollection<string> WordSizes { get; } = new();
    public ObservableCollection<string> SolidBlockSizes { get; } = new();
    public ObservableCollection<string> ThreadOptions { get; } = new();
    public ObservableCollection<string> EncryptionMethodOptions { get; } = new();
    public ObservableCollection<string> VolumePresets { get; } = new();
    public ObservableCollection<string> SourceItems { get; } = new();
    public ObservableCollection<ExclusionItem> Exclusions { get; } = new();

    // --- Static option lists ---
    public static string[] Formats { get; } = { "7z", "zip", "tar", "gzip", "bzip2", "xz", "wim" };
    public static string[] Levels { get; } = { "0 - 仅存储", "1 - 最快", "3 - 快速", "5 - 普通", "7 - 最大", "9 - 极限" };
    public static string[] UpdateMethods { get; } = { "添加并替换文件", "更新并添加文件", "更新已有文件", "同步文件" };
    public static string[] PathModes { get; } = { "相对路径", "绝对路径", "不保存路径" };
    public static string[] VolumeModes { get; } = { "预设", "手动" };
    public static string[] VolumeUnits { get; } = { "B", "KB", "MB", "GB" };
    public static string SystemThreadCountDisplay { get; } = $"/ {Environment.ProcessorCount}";
    public bool IsVolumePresetMode => IsVolumeSplitEnabled && SelectedVolumeMode == "预设";
    public bool IsVolumeCustomMode => IsVolumeSplitEnabled && SelectedVolumeMode == "手动";

    // --- Data tables (from 7-zip source CompressDialog.cpp) ---

    // LZMA/LZMA2: dict sizes using formula (2+(i&1))<<(i/2) starting from i=30,34,38,40...
    private static readonly string[] _lzmaDictSizes =
    {
        "64 KB", "256 KB",
        "1 MB", "2 MB", "3 MB", "4 MB", "6 MB", "8 MB", "12 MB", "16 MB",
        "24 MB", "32 MB", "48 MB", "64 MB", "96 MB", "128 MB", "192 MB",
        "256 MB", "384 MB", "512 MB", "768 MB", "1024 MB", "1536 MB"
    };

    // LZMA/LZMA2: order/fast-bytes: (2+(i&1))<<(i/2) for i=4..15, capped at 273
    private static readonly string[] _lzmaWordSizes =
        { "8", "12", "16", "24", "32", "48", "64", "96", "128", "192", "256", "273" };

    // PPMd: dict sizes starting at 1 MB, same formula from i=38
    private static readonly string[] _ppmdDictSizes =
    {
        "1 MB", "2 MB", "3 MB", "4 MB", "6 MB", "8 MB", "12 MB", "16 MB",
        "24 MB", "32 MB", "48 MB", "64 MB", "96 MB", "128 MB", "192 MB", "256 MB"
    };

    // PPMd: order values: 2,3,4,5,6,7,8,10,12,14,16,20,24,28,32
    private static readonly string[] _ppmdWordSizes =
        { "2", "3", "4", "5", "6", "7", "8", "10", "12", "14", "16", "20", "24", "28", "32" };

    // BZip2: 100KB steps from 100KB to 900KB
    private static readonly string[] _bzip2DictSizes =
        { "100 KB", "200 KB", "300 KB", "400 KB", "500 KB", "600 KB", "700 KB", "800 KB", "900 KB" };

    // Deflate/Deflate64: same word sizes as LZMA, capped at 258
    private static readonly string[] _deflateWordSizes =
        { "8", "12", "16", "24", "32", "48", "64", "96", "128", "192", "256", "258" };

    // Solid block sizes for 7z (powers of 2 from 1MB to 4GB, plus non-solid and full-solid)
    private static readonly string[] _solidBlockSizes =
    {
        "非固实",
        "1 MB", "2 MB", "4 MB", "8 MB", "16 MB", "32 MB", "64 MB",
        "128 MB", "256 MB", "512 MB", "1 GB", "2 GB", "4 GB",
        "固实"
    };

    private static readonly string[] _volumePresets =
    {
        "10M",
        "100M",
        "1000M",
        "650M - CD",
        "700M - CD",
        "4092M - FAT",
        "4480M - DVD",
        "8128M - DVD DL",
        "23040M - BD"
    };

    // --- Delegates injected from code-behind ---
    public Action? CloseAction { get; set; }
    public Action? ExitApplicationAction { get; set; }
    public Func<Task<IStorageFolder?>>? BrowseArchiveFolderAction { get; set; }
    public Func<string, Task<IReadOnlyList<IStorageFile>?>>? PickFilesAction { get; set; }
    public Func<string, Task<IReadOnlyList<IStorageFolder>?>>? PickFoldersAction { get; set; }

    public CompressWindowViewModel(SevenZipService sevenZip, SettingsService settings)
    {
        _sevenZip = sevenZip;
        _settings = settings;
        _selectedFormat = settings.Settings.DefaultFormat;
        _selectedLevel = LevelFromInt(settings.Settings.DefaultCompressionLevel);
        _selectedEncryption = settings.Settings.DefaultEncryptionMethod;
        _updateMethod = UpdateMethodToDisplay(settings.Settings.DefaultUpdateMethod);
        _pathMode = PathModeToDisplay(settings.Settings.DefaultPathMode);

        // Build thread options: Auto, then 1..max(cpuCount, 8)
        int cpuCount = Environment.ProcessorCount;
        ThreadOptions.Add("自动");
        int maxT = Math.Max(cpuCount, 8);
        for (int i = 1; i <= maxT; i++) ThreadOptions.Add(i.ToString());
        // Extend to common round numbers above cpu count
        foreach (int extra in new[] { 16, 24, 32, 48, 64 })
            if (extra > maxT) ThreadOptions.Add(extra.ToString());

        foreach (var preset in _volumePresets)
            VolumePresets.Add(preset);

        // Initialize all dependent combos
        ApplyFormat(_selectedFormat);
        SelectedVolumePreset = VolumePresets.FirstOrDefault() ?? "";
        SyncVolumeInput();
    }

    // ===== Format change cascade =====

    private void ApplyFormat(string format)
    {
        if (_updating) return;
        _updating = true;

        Methods.Clear();
        string[] methodList = format switch
        {
            "7z"    => new[] { "LZMA2", "LZMA", "PPMd", "BZip2", "Copy" },
            "zip"   => new[] { "Deflate", "Deflate64", "BZip2", "LZMA", "PPMd", "Copy" },
            "gzip"  => new[] { "Deflate", "Copy" },
            "bzip2" => new[] { "BZip2", "Copy" },
            "xz"    => new[] { "LZMA2", "Copy" },
            "tar"   => new[] { "Copy" },
            "wim"   => new[] { "Copy" },
            _        => Array.Empty<string>()
        };
        foreach (var m in methodList) Methods.Add(m);

        // Solid block size
        IsSolidEnabled = format == "7z" || format == "xz";
        SolidBlockSizes.Clear();
        if (IsSolidEnabled)
            foreach (var s in _solidBlockSizes) SolidBlockSizes.Add(s);

        // Encryption
        EncryptionMethodOptions.Clear();
        IsEncryptionEnabled = format == "7z" || format == "zip";
        IsEncryptFileNamesEnabled = format == "7z";
        if (format == "7z")
            EncryptionMethodOptions.Add("AES-256");
        else if (format == "zip")
        { EncryptionMethodOptions.Add("AES-256"); EncryptionMethodOptions.Add("ZipCrypto"); }
        if (EncryptionMethodOptions.Count > 0 && !EncryptionMethodOptions.Contains(SelectedEncryption))
            SelectedEncryption = EncryptionMethodOptions[0];

        string defaultMethod = format switch
        {
            "7z"    => "LZMA2",
            "zip"   => "Deflate",
            "gzip"  => "Deflate",
            "bzip2" => "BZip2",
            "xz"    => "LZMA2",
            _       => "Copy"
        };

        _updating = false;

        SelectedMethod = Methods.Contains(defaultMethod) ? defaultMethod
                       : Methods.Count > 0 ? Methods[0] : "";

        // Solid default
        if (IsSolidEnabled)
            SelectedSolidBlockSize = SolidBlockSizes.Contains("固实") ? "固实" : "";
        else
            SelectedSolidBlockSize = "";

        RefreshControlStates();
    }

    // ===== Method change cascade =====

    private void ApplyMethod(string method)
    {
        if (_updating) return;
        _updating = true;

        DictionarySizes.Clear();
        WordSizes.Clear();

        string[]? dictSrc = method switch
        {
            "LZMA" or "LZMA2"          => _lzmaDictSizes,
            "PPMd"                     => _ppmdDictSizes,
            "BZip2"                    => _bzip2DictSizes,
            "Deflate"                  => new[] { "32 KB" },
            "Deflate64"                => new[] { "64 KB" },
            _                          => null
        };
        if (dictSrc != null) foreach (var d in dictSrc) DictionarySizes.Add(d);

        string[]? wordSrc = method switch
        {
            "LZMA" or "LZMA2"          => _lzmaWordSizes,
            "PPMd"                     => _ppmdWordSizes,
            "Deflate" or "Deflate64"   => _deflateWordSizes,
            _                          => null
        };
        if (wordSrc != null) foreach (var w in wordSrc) WordSizes.Add(w);

        // Limit thread options by method
        RebuildThreadOptionsForMethod(method);

        _updating = false;

        ApplyLevelDefaults(SelectedLevel, method);
        RefreshControlStates();
    }

    private void RebuildThreadOptionsForMethod(string method)
    {
        // Max threads per method (from 7-zip SetNumThreads2)
        int maxForMethod = method switch
        {
            "LZMA"                                        => 2,
            "PPMd" or "Deflate" or "Deflate64" or "Copy" => 1,
            _                                             => Math.Min(Environment.ProcessorCount, 64)
        };

        ThreadOptions.Clear();
        ThreadOptions.Add("自动");
        int maxT = Math.Max(maxForMethod, 1);
        for (int i = 1; i <= maxT; i++) ThreadOptions.Add(i.ToString());

        // Keep SelectedThreads valid
        if (!ThreadOptions.Contains(SelectedThreads))
            SelectedThreads = "自动";

        IsThreadCountEnabled = ThreadOptions.Count > 1;
    }

    // ===== Level defaults cascade =====

    private void ApplyLevelDefaults(string level, string method)
    {
        if (string.IsNullOrWhiteSpace(method)) return;

        int lvl = LevelToInt(level);

        if (method is "LZMA" or "LZMA2")
        {
            // _auto_Dict = level<=4 ? 1<<(lvl*2+16) : 1<<(lvl+20)  (64-bit)
            long autoDict = lvl <= 4
                ? (1L << (lvl * 2 + 16))
                : (1L << (lvl + 20));
            string dictDefault = ClosestDictSize(DictionarySizes, autoDict);
            string wordDefault = lvl < 7 ? "32" : "64";

            SelectedDictionarySize = dictDefault;
            SelectedWordSize = WordSizes.Contains(wordDefault) ? wordDefault
                             : WordSizes.Count > 0 ? WordSizes[0] : "";
        }
        else if (method == "PPMd")
        {
            // _auto_Dict = 1<<(lvl+19)
            long autoDict = 1L << (lvl + 19);
            string dictDefault = ClosestDictSize(DictionarySizes, autoDict);
            string wordDefault = lvl >= 9 ? "32" : lvl >= 7 ? "16" : lvl >= 5 ? "6" : "4";

            SelectedDictionarySize = dictDefault;
            SelectedWordSize = WordSizes.Contains(wordDefault) ? wordDefault
                             : WordSizes.Count > 0 ? WordSizes[0] : "";
        }
        else if (method == "BZip2")
        {
            string dictDefault = lvl >= 5 ? "900 KB" : lvl >= 3 ? "500 KB" : "100 KB";
            SelectedDictionarySize = DictionarySizes.Contains(dictDefault)
                ? dictDefault : DictionarySizes.Count > 0 ? DictionarySizes[0] : "";
            SelectedWordSize = "";
        }
        else if (method is "Deflate" or "Deflate64")
        {
            SelectedDictionarySize = DictionarySizes.Count > 0 ? DictionarySizes[0] : "";
            string wordDefault = lvl >= 9 ? "128" : lvl >= 7 ? "64" : "32";
            SelectedWordSize = WordSizes.Contains(wordDefault) ? wordDefault
                             : WordSizes.Count > 0 ? WordSizes[0] : "";
        }
        else
        {
            SelectedDictionarySize = "";
            SelectedWordSize = "";
        }

        UpdateMemoryUsage();
    }

    private static string ClosestDictSize(ObservableCollection<string> sizes, long targetBytes)
    {
        if (sizes.Count == 0) return "";
        string best = sizes[0];
        long bestDiff = long.MaxValue;
        foreach (var s in sizes)
        {
            long bytes = ParseSizeBytes(s);
            long diff = Math.Abs(bytes - targetBytes);
            if (diff < bestDiff) { bestDiff = diff; best = s; }
        }
        return best;
    }

    // ===== Memory usage =====

    private void UpdateMemoryUsage()
    {
        var (comp, decomp) = CalculateMemory();
        MemoryCompress   = comp   > 0 ? $"{comp} MB"   : "—";
        MemoryDecompress = decomp > 0 ? $"{decomp} MB" : "—";
    }

    private (long compress, long decomp) CalculateMemory()
    {
        string method = SelectedMethod;
        if (string.IsNullOrWhiteSpace(method) || method == "Copy") return (1, 1);

        long dictMB = ParseSizeBytes(SelectedDictionarySize) / (1024 * 1024);
        if (dictMB < 1) dictMB = 1;

        int threads = int.TryParse(SelectedThreads, out var t) ? t : Environment.ProcessorCount;
        if (threads < 1) threads = 1;

        return method switch
        {
            "LZMA"   => (dictMB * 3 + 10, dictMB + 4),
            "LZMA2"  => ((long)Math.Ceiling(threads / 2.0) * (dictMB * 3) + 10, dictMB + 4),
            "PPMd"   => (dictMB + 4, dictMB + 4),
            "BZip2"  => (10, 4),
            "Deflate" or "Deflate64" => (2, 2),
            _        => (1, 1)
        };
    }

    // ===== Property changed handlers =====

    partial void OnSelectedFormatChanged(string value)
    {
        if (!_updating) ApplyFormat(value);
        UpdateDefaultArchivePath();
    }

    partial void OnSelectedMethodChanged(string value)
    {
        if (!string.IsNullOrWhiteSpace(value) && !_updating) ApplyMethod(value);
        RefreshControlStates();
    }

    partial void OnSelectedLevelChanged(string value)
    {
        NormalizeMethodForLevel();
        if (!string.IsNullOrWhiteSpace(SelectedMethod) && !_updating)
            ApplyLevelDefaults(value, SelectedMethod);
        RefreshControlStates();
    }

    partial void OnSelectedDictionarySizeChanged(string value) => UpdateMemoryUsage();
    partial void OnSelectedThreadsChanged(string value)        => UpdateMemoryUsage();
    partial void OnArchivePathChanged(string value)
    {
        if (_isUpdatingArchivePath) return;
        _archivePathAutoGenerated = string.IsNullOrWhiteSpace(value);
    }

    partial void OnSelectedVolumeModeChanged(string value)
    {
        OnPropertyChanged(nameof(IsVolumePresetMode));
        OnPropertyChanged(nameof(IsVolumeCustomMode));
        SyncVolumeInput();
    }

    partial void OnIsVolumeSplitEnabledChanged(bool value)
    {
        if (!value)
        {
            SelectedVolumeMode = "";
            VolumeCustomSize = "";
            VolumeSize = "";
        }
        else if (string.IsNullOrWhiteSpace(SelectedVolumeMode))
        {
            SelectedVolumeMode = VolumeModes[0];
        }

        OnPropertyChanged(nameof(IsVolumePresetMode));
        OnPropertyChanged(nameof(IsVolumeCustomMode));
        SyncVolumeInput();
    }

    partial void OnSelectedVolumePresetChanged(string value) => SyncVolumeInput();
    partial void OnVolumeCustomSizeChanged(string value) => SyncVolumeInput();
    partial void OnSelectedVolumeUnitChanged(string value) => SyncVolumeInput();
    partial void OnCreateSfxChanged(bool value) => RefreshControlStates();

    // ===== Source items =====

    public void AddSourceItems(IEnumerable<string> items)
    {
        bool added = false;
        foreach (var item in items)
        {
            if (SourceItems.Contains(item)) continue;
            SourceItems.Add(item);
            added = true;
        }

        if (added) UpdateDefaultArchivePath();
    }

    public void SetSelectedSourceItems(IEnumerable<string> items)
    {
        SelectedSources.Clear();
        foreach (var item in items)
            SelectedSources.Add(item);
    }

    public void SetSelectedExclusions(IEnumerable<ExclusionItem> items)
    {
        SelectedExclusions.Clear();
        foreach (var item in items)
            SelectedExclusions.Add(item);
    }

    private void UpdateDefaultArchivePath()
    {
        if (SourceItems.Count == 0) return;
        if (!_archivePathAutoGenerated && !string.IsNullOrWhiteSpace(ArchivePath)) return;

        var first = SourceItems[0];
        bool isFile = File.Exists(first);
        var dir = isFile
            ? Path.GetDirectoryName(first) ?? ""
            : Path.GetDirectoryName(first.TrimEnd('\\', '/')) ?? "";
        var archiveName = GetSuggestedArchiveFileName(first, isFile);
        SetArchivePath(Path.Combine(dir, archiveName));
    }

    private string GetSuggestedArchiveFileName(string? sourcePath = null, bool? isFile = null)
    {
        var first = sourcePath ?? SourceItems.FirstOrDefault() ?? "archive";
        bool currentIsFile = isFile ?? File.Exists(first);
        var name = Path.GetFileNameWithoutExtension(currentIsFile ? first : first.TrimEnd('\\', '/'));
        var ext = SelectedFormat switch
        {
            "gzip"  => "gz",
            "bzip2" => "bz2",
            _       => SelectedFormat
        };

        if (string.IsNullOrWhiteSpace(name))
            name = "archive";

        return $"{name}.{ext}";
    }

    private void SetArchivePath(string path)
    {
        _isUpdatingArchivePath = true;
        ArchivePath = path;
        _archivePathAutoGenerated = true;
        _isUpdatingArchivePath = false;
    }

    // ===== Commands =====

    [RelayCommand]
    private async Task BrowseArchive()
    {
        if (BrowseArchiveFolderAction == null) return;
        var folder = await BrowseArchiveFolderAction();
        if (folder == null) return;

        var fileName = Path.GetFileName(ArchivePath);
        if (string.IsNullOrWhiteSpace(fileName) || !Path.HasExtension(fileName))
            fileName = GetSuggestedArchiveFileName();

        SetArchivePath(Path.Combine(folder.Path.LocalPath, fileName));
    }

    [RelayCommand]
    private async Task AddSourceFiles()
    {
        if (PickFilesAction == null) return;
        var files = await PickFilesAction("选择要压缩的文件");
        if (files == null) return;
        AddSourceItems(files.Select(f => f.Path.LocalPath));
        ProgressText = $"已添加 {files.Count} 个文件。";
    }

    [RelayCommand]
    private async Task AddSourceFolders()
    {
        if (PickFoldersAction == null) return;
        var folders = await PickFoldersAction("选择要压缩的文件夹");
        if (folders == null) return;
        AddSourceItems(folders.Select(folder => folder.Path.LocalPath));
        ProgressText = $"已添加 {folders.Count} 个文件夹。";
    }

    [RelayCommand]
    private void RemoveSourceItems()
    {
        var toRemove = SelectedSources.ToList();
        foreach (var item in toRemove)
            SourceItems.Remove(item);
        SelectedSources.Clear();

        if (SourceItems.Count == 0 && _archivePathAutoGenerated)
            SetArchivePath(string.Empty);
        else
            UpdateDefaultArchivePath();
    }

    [RelayCommand]
    private async Task AddExclusionFiles()
    {
        if (PickFilesAction == null) return;
        var files = await PickFilesAction("选择要排除的文件");
        if (files == null) return;
        foreach (var f in files)
            AddExclusionItem(new ExclusionItem { Path = f.Path.LocalPath, IsFolder = false, IsRecursive = true });
    }

    [RelayCommand]
    private async Task AddExclusionFolder()
    {
        if (PickFoldersAction == null) return;
        var folders = await PickFoldersAction("选择要排除的文件夹");
        if (folders == null) return;
        foreach (var folder in folders)
            AddExclusionItem(new ExclusionItem { Path = folder.Path.LocalPath, IsFolder = true, IsRecursive = true });
    }

    [RelayCommand]
    private void AddExclusionPattern()
    {
        var pattern = PatternInput.Trim();
        if (string.IsNullOrWhiteSpace(pattern)) return;
        AddExclusionItem(new ExclusionItem { Path = pattern, IsFolder = false, IsRecursive = true });
        PatternInput = "";
    }

    [RelayCommand]
    private void RemoveExclusions()
    {
        var toRemove = SelectedExclusions.ToList();
        foreach (var item in toRemove) Exclusions.Remove(item);
        SelectedExclusions.Clear();
    }

    [RelayCommand]
    private async Task Compress()
    {
        if (SourceItems.Count == 0)
        {
            ProgressText = "请先添加至少一个要压缩的文件或文件夹。";
            return;
        }

        if (string.IsNullOrWhiteSpace(ArchivePath))
        {
            ProgressText = "请先确认保存文件路径。";
            return;
        }

        if (!File.Exists(_settings.Settings.SevenZipPath))
        {
            ProgressText = $"7-Zip 路径无效：{_settings.Settings.SevenZipPath}";
            return;
        }

        if (!string.IsNullOrWhiteSpace(Password) && Password != PasswordConfirm)
        {
            ProgressText = "错误：两次输入的密码不一致！";
            return;
        }

        if (!IsVolumeInputValid(out var volumeError))
        {
            ProgressText = volumeError;
            return;
        }

        IsRunning = true;
        ProgressText = "正在压缩...";
        try
        {
            var opts = BuildOptions();
            var progress = new Progress<string>(line => ProgressText = line);
            var (success, _, error) = await _sevenZip.CompressAsync(opts, progress);
            ProgressText = success ? "✅ 压缩完成！" : $"❌ 失败: {error}";

            if (success)
            {
                ExitApplicationAction?.Invoke();
            }
        }
        finally
        {
            IsRunning = false;
        }
    }

    [RelayCommand]
    private void Cancel() => CloseAction?.Invoke();

    // ===== Build options =====

    private CompressionOptions BuildOptions() => new()
    {
        SourceItems        = SourceItems.ToList(),
        ArchivePath        = ArchivePath,
        Format             = SelectedFormat,
        Level              = LevelToInt(SelectedLevel),
        Method             = SelectedMethod,
        DictionarySize     = SizeToCli(SelectedDictionarySize),
        WordSize           = SelectedWordSize,
        SolidBlockSize     = SolidToCli(SelectedSolidBlockSize),
        Threads            = SelectedThreads == "自动" ? "" : SelectedThreads,
        Password           = Password,
        EncryptFileNames   = EncryptFileNames,
        EncryptionMethod   = SelectedEncryption,
        Exclusions         = Exclusions.ToList(),
        UpdateMethod       = UpdateMethodFromDisplay(UpdateMethod),
        PathMode           = PathModeFromDisplay(PathMode),
        CreateSfx          = CreateSfx,
        CompressSharedFiles = CompressSharedFiles,
        DeleteAfterCompress = DeleteAfterCompress,
        VolumeSize         = VolumeSize,
        AdditionalParameters = AdditionalParams,
    };

    public string GetCommandPreview()
    {
        var opts = BuildOptions();
        var args = _sevenZip.BuildCompressArgs(opts);
        return $"\"{_settings.Settings.SevenZipPath}\" {string.Join(" ", args)}";
    }

    // ===== Helpers =====

    private static long ParseSizeBytes(string display)
    {
        if (string.IsNullOrWhiteSpace(display)) return 0;
        var parts = display.Trim().Split(' ');
        if (parts.Length != 2 || !long.TryParse(parts[0], out long num)) return 0;
        return parts[1].ToUpperInvariant() switch
        {
            "B"  => num,
            "KB" => num * 1024L,
            "MB" => num * 1024L * 1024,
            "GB" => num * 1024L * 1024 * 1024,
            _    => 0
        };
    }

    private static string SizeToCli(string display)
    {
        if (string.IsNullOrWhiteSpace(display)) return "";
        var parts = display.Trim().Split(' ');
        if (parts.Length != 2) return display;
        return parts[1].ToUpperInvariant() switch
        {
            "B"  => parts[0],
            "KB" => $"{parts[0]}k",
            "MB" => $"{parts[0]}m",
            "GB" => $"{parts[0]}g",
            _    => display
        };
    }

    private static string SolidToCli(string display) => display switch
    {
        "" or null    => "",
        "非固实"       => "off",
        "固实"         => "on",
        _             => SizeToCli(display)
    };

    private static int LevelToInt(string s) => s.Length > 0 && char.IsDigit(s[0]) ? s[0] - '0' : 5;
    private static string LevelFromInt(int n) => Levels.FirstOrDefault(l => l[0] - '0' == n) ?? "5 - 普通";

    private static string ExtractVolumePreset(string preset)
    {
        if (string.IsNullOrWhiteSpace(preset)) return "";
        return preset.Split(' ', StringSplitOptions.RemoveEmptyEntries)[0].Trim();
    }

    private static string UnitToCliSuffix(string unit) => unit switch
    {
        "KB" => "k",
        "MB" => "m",
        "GB" => "g",
        _ => ""
    };

    private void SyncVolumeInput()
    {
        if (!IsVolumeEnabled || !IsVolumeSplitEnabled)
        {
            VolumeSize = "";
            return;
        }

        if (string.IsNullOrWhiteSpace(SelectedVolumeMode))
        {
            VolumeSize = "";
            return;
        }

        if (IsVolumePresetMode)
        {
            VolumeSize = ExtractVolumePreset(SelectedVolumePreset);
            return;
        }

        var raw = VolumeCustomSize.Trim();
        VolumeSize = string.IsNullOrWhiteSpace(raw) ? "" : $"{raw}{UnitToCliSuffix(SelectedVolumeUnit)}";
    }

    private bool IsVolumeInputValid(out string error)
    {
        error = "";

        if (string.IsNullOrWhiteSpace(VolumeSize))
            return true;

        if (IsVolumePresetMode)
            return true;

        if (!decimal.TryParse(VolumeCustomSize.Trim(), out var number) || number <= 0)
        {
            error = "分卷大小无效，请输入大于 0 的数字。";
            return false;
        }

        return true;
    }

    private void NormalizeMethodForLevel()
    {
        if (_updating || Methods.Count == 0) return;

        if (LevelToInt(SelectedLevel) == 0)
        {
            if (Methods.Contains("Copy") && SelectedMethod != "Copy")
                SelectedMethod = "Copy";
            return;
        }

        if (SelectedMethod == "Copy")
        {
            var preferred = SelectedFormat switch
            {
                "7z" => "LZMA2",
                "zip" => "Deflate",
                "gzip" => "Deflate",
                "bzip2" => "BZip2",
                "xz" => "LZMA2",
                _ => "Copy"
            };

            if (Methods.Contains(preferred))
                SelectedMethod = preferred;
        }
    }

    private void RefreshControlStates()
    {
        var level = LevelToInt(SelectedLevel);
        var isCopy = string.Equals(SelectedMethod, "Copy", StringComparison.OrdinalIgnoreCase);

        IsMethodEnabled = Methods.Count > 0;
        IsDictionaryEnabled = level > 0 && !isCopy && DictionarySizes.Count > 1;
        IsWordSizeEnabled = level > 0 && !isCopy && WordSizes.Count > 0;
        IsSolidEnabled = (SelectedFormat == "7z" || SelectedFormat == "xz") && level > 0 && !isCopy && SolidBlockSizes.Count > 0;
        IsThreadCountEnabled = ThreadOptions.Count > 1;
        IsSfxEnabled = SelectedFormat == "7z" && (SelectedMethod == "LZMA" || SelectedMethod == "LZMA2" || SelectedMethod == "Copy");

        if (!IsSfxEnabled && CreateSfx)
            CreateSfx = false;

        IsVolumeEnabled = !CreateSfx;
        if (!IsVolumeEnabled)
        {
            IsVolumeSplitEnabled = false;
            VolumeSize = "";
        }

        SyncVolumeInput();
        UpdateMemoryUsage();
    }

    private void AddExclusionItem(ExclusionItem item)
    {
        if (Exclusions.Any(existing => string.Equals(existing.Path, item.Path, StringComparison.OrdinalIgnoreCase)
            && existing.IsFolder == item.IsFolder
            && existing.IsRecursive == item.IsRecursive))
        {
            return;
        }

        Exclusions.Add(item);
    }

    private static string UpdateMethodFromDisplay(string s) => s switch
    {
        "添加并替换文件" => "Add and replace files",
        "更新并添加文件" => "Update and add files",
        "更新已有文件"  => "Freshen existing files",
        "同步文件"      => "Synchronize files",
        _               => "Add and replace files"
    };

    private static string UpdateMethodToDisplay(string s) => s switch
    {
        "Add and replace files" => "添加并替换文件",
        "Update and add files"  => "更新并添加文件",
        "Freshen existing files" => "更新已有文件",
        "Synchronize files"     => "同步文件",
        _                       => "添加并替换文件"
    };

    private static string PathModeFromDisplay(string s) => s switch
    {
        "相对路径" => "Relative pathnames",
        "绝对路径" => "Absolute pathnames",
        "不保存路径" => "No pathnames",
        _          => "Relative pathnames"
    };

    private static string PathModeToDisplay(string s) => s switch
    {
        "Relative pathnames" => "相对路径",
        "Absolute pathnames" => "绝对路径",
        "No pathnames"       => "不保存路径",
        _                    => "相对路径"
    };
}
